import * as stylex from '@stylexjs/stylex'

import { colors, radius, space } from './tokens.stylex'

export const ui = stylex.create({
	main: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.lg,
		maxWidth: '1080px',
		marginInline: 'auto',
		paddingBlock: space.xl,
		paddingInline: space.md,
	},
	centered: {
		display: 'grid',
		placeItems: 'center',
		minHeight: '100svh',
		padding: space.md,
	},
	grid: {
		display: 'grid',
		gap: space.md,
		gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
		alignItems: 'start',
	},
	card: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.sm,
		padding: space.lg,
		backgroundColor: colors.surface,
		borderColor: colors.border,
		borderStyle: 'solid',
		borderWidth: '1px',
		borderRadius: radius.card,
	},
	narrow: { width: '100%', maxWidth: '420px' },
	eyebrow: { fontSize: '0.75rem', fontWeight: 500, color: colors.muted },
	title: { fontSize: '2.25rem', fontWeight: 600, letterSpacing: '-0.02em' },
	heading: { fontSize: '1.25rem', fontWeight: 600 },
	muted: { fontSize: '0.875rem', color: colors.muted },
	error: { fontSize: '0.875rem', color: colors.danger },
	list: { display: 'flex', flexDirection: 'column', gap: space.sm },
	row: { display: 'flex', alignItems: 'center', gap: space.sm },
	grow: { flexGrow: 1, minWidth: 0 },
	done: { color: colors.muted, textDecoration: 'line-through' },
	button: {
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		gap: space.sm,
		height: '36px',
		paddingInline: space.md,
		borderStyle: 'solid',
		borderWidth: '1px',
		borderColor: colors.accent,
		borderRadius: radius.control,
		backgroundColor: colors.accent,
		color: colors.onAccent,
		fontSize: '0.875rem',
		fontWeight: 500,
		textDecoration: 'none',
		cursor: { default: 'pointer', ':disabled': 'default' },
		opacity: { default: 1, ':disabled': 0.6 },
	},
	outline: {
		borderColor: colors.border,
		backgroundColor: 'transparent',
		color: colors.text,
	},
	ghost: {
		borderColor: 'transparent',
		backgroundColor: 'transparent',
		color: colors.muted,
	},
	input: {
		height: '36px',
		paddingInline: space.sm,
		borderStyle: 'solid',
		borderWidth: '1px',
		borderColor: colors.border,
		borderRadius: radius.control,
		backgroundColor: 'transparent',
		outlineColor: colors.accent,
		outlineStyle: { default: 'none', ':focus-visible': 'solid' },
		outlineWidth: '2px',
	},
	todo: {
		padding: space.sm,
		borderStyle: 'solid',
		borderWidth: '1px',
		borderColor: colors.border,
		borderRadius: radius.control,
	},
	plain: {
		flexGrow: 1,
		minWidth: 0,
		padding: 0,
		borderWidth: 0,
		backgroundColor: 'transparent',
		textAlign: 'start',
		cursor: 'pointer',
	},
})
